version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "krafs"
    ignore:
      - dependency-name: "Krafs.Rimworld.Ref"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "krafs"