version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "krafs"
    labels:
      - "build"
    commit-message:
      prefix: "build"