name: CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 8.0.x
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Zip release
      run: zip -9 -r LevelUp${{ github.event.inputs.version }}.zip LevelUp/
      working-directory: bin

    - name: Publish draft release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/LevelUp*.zip
        tag_name: v${{ github.event.inputs.version }}
        fail_on_unmatched_files: true
        token: ${{ github.token }}
        draft: true
