name: CI/CD

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -property:ModOutput=./ --no-restore -warnaserror

    - name: Resolve version
      run: echo "VERSION=$(git describe --tag --abbrev=0)" >> $GITHUB_ENV

    - name: Zip release
      run: zip -9 -r LevelUp${{ env.VERSION }}.zip LevelUp

    - name: Publish draft release
      uses: softprops/action-gh-release@v1
      with:
        files: LevelUp*.zip
        tag_name: ${{ env.VERSION }}
        fail_on_unmatched_files: true
        token: ${{ github.token }}
        draft: true